export const GAMIFICATION_STORAGE_KEY = 'crjm.gamification.v1';

export {
  createInitialProfile,
  getLevelFromXp,
  getLevelTitle,
  getMissionProgress,
  getXpWindow,
  claimMissionReward,
  recordGameCompletion,
  recordPatternProgress,
  recordPuzzleSolved,
  recordReviewCompletion,
  rebuildProfileFromEvents,
  sanitizeProfile,
  type AchievementPopupState,
  type AchievementUnlock,
  type GamificationEvent,
  type GamificationProfile,
  type GameProgressSnapshot,
  type MissionProgress,
  type PatternEvidence,
  type PatternProgress,
  type PatternState,
} from '../../ai-core/learner-gamification';
